language: go

go:
  - "1.11"

script: go test ./...

before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker tag "$IMAGE_NAME" "$IMAGE_NAME:latest"
        - docker tag "$IMAGE_NAME" "$IMAGE_NAME:${version}"
deploy:
        provider: script
        script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
        on:
                branch: master

